PlayerCount <- 10

RNGData <- data.frame("Biome" = c("Taiga",
                                  "Taiga Hills",
                                  "Taiga M",
                                  "Beach",
                                  "Stone Beach",
                                  "Cold Beach",
                                  "Plains",
                                  "Sunflower Plains",
                                  "Ocean",
                                  "Deep Ocean",
                                  "Frozen Ocean",
                                  "The End",
                                  "Birch Forest",
                                  "Birch Forest Hills",
                                  "Birch Forest M",
                                  "Birch Forest Hills M",
                                  "Mushroom Island",
                                  "Mushroom Island Shore",
                                  "Desert",
                                  "Desert Hills",
                                  "Desert M",
                                  "Savanna",
                                  "Savanna Plateau",
                                  "Savanna M",
                                  "Savanna Plateau M",
                                  "Mesa",
                                  "Mesa Plateau",
                                  "Mesa Plateau F",
                                  "Mesa (Bryce)",
                                  "Mesa Plateau M",
                                  "Mesa Plateau F M",
                                  "Hell",
                                  "Swampland",
                                  "Swampland M",
                                  "Ice Mountains",
                                  "Cold Taiga Hills",
                                  "Cold Taiga M",
                                  "Extreme Hills",
                                  "Extreme Hills+",
                                  "Extreme Hills+ M",
                                  "Extreme Hills Edge",
                                  "Extreme Hills M",
                                  "Jungle",
                                  "Jungle Edge",
                                  "Jungle Hills",
                                  "Jungle M",
                                  "Jungle Edge M",
                                  "Forest",
                                  "Forest Hills",
                                  "Roofed Forest",
                                  "Roofed Forest M",
                                  "Flower Forest",
                                  "Cold Taiga",
                                  "Frozen River",
                                  "Ice Plains",
                                  "Ice Plains Spikes",
                                  "Mega Taiga",
                                  "Mega Taiga Hills",
                                  "Mega Spruce Taiga",
                                  "Redwood Taiga Hills M",
                                  "River"),
                      "ID" = NA)
RNGData[,2] <- seq(1, length(RNGData$Biome), by = 1)
Players <- data.frame("Player" = seq(1, PlayerCount, by = 1),
                      "Biome" = NA,
                      "BiomeID" = sample(RNGData$ID, PlayerCount))
Players$Biome <- RNGData$Biome[match(Players$BiomeID, RNGData$ID)]
